blueprint:
  name: Mac feeding reminder
  description: 
  domain: automation
  input:
    reminder_time:
      name: Reminder time
      description: At what time do you want to be reminded
      selector:
        time: {}

    notify_device:
      name: Notification
      description:
      selector:
        device:
          integration: mobile_app
          multiple: true

    input_boolean:
      name: Dedicated input_boolean
      description: 
      selector:
        entity:
          domain: input_boolean
          multiple: false

    notification_title:
      name: Notification title (Optional)
      description: ""
      default: "Mac feeding reminder!"

    notification_message:
      name: Notification message (Optional)
      description: ""
      default: "It's time to feed Mac"

    notification_action_taken:
      name: "Notification action: Fed (Optional)"
      description: ""
      default: "fed"

    notification_action_later:
      name: "Notification action: Ask later (Optional)"
      description: ""
      default: "Ask later"

    notification_action_skip:
      name: "Notification action: Skip (Optional)"
      description: ""
      default: "Skip"

    ask_later_wait_time:
      name: Wait time before next reminder
      description: Minutes before notify again after a Ask later action.
      default: 30
      selector:
        number:
          min: 5
          max: 1440
          unit_of_measurement: minutes
          step: 1
          mode: slider

    logbook_message_remind:
      name: Logbook message for remind (Optional)
      description: "Default: Reminder sent"
      default: "Reminder sent"

    logbook_message_taken:
      name: Logbook message for action Taken (Optional)
      description: ""
      default: "Mac fed"

    logbook_message_later:
      name: Logbook message for action Ask later (Optional)
      description: ""
      default: "Postpone reminder"

    logbook_message_skip:
      name: Logbook message for action Skip (Optional)
      description: ""
      default: "Reminder skipped"

    logbook_message_no_answer:
      name: Logbook message for no action after timeout (Optional)
      description: ""
      default: "No answer time out"

trigger:
  - platform: time
    at: !input reminder_time

mode: restart

action:
  - service: input_boolean.turn_off
    target:
      entity_id: !input input_boolean
  - alias: "Notify until the Mac has been fed"
    repeat:
      while:
        - condition: state
          entity_id: !input input_boolean
          state: "off"
      sequence:
        - service: logbook.log
          data:
            name: !input notification_title
            message: !input logbook_message_remind
            entity_id: !input input_boolean
        - choose:
            - conditions: "{{ true }}"
              sequence: !input optional_action
        - device_id: !input notify_device
          domain: mobile_app
          type: notify
          title: !input notification_title
          message: !input notification_message
          data:
            actions:
              - title: !input notification_action_taken
                action: "fed"
              - title: !input notification_action_later
                action: "later"
              - title: !input notification_action_skip
                action: "skip"
            tag: !input input_boolean
        - wait_for_trigger:
            platform: event
            event_type: ios.notification_action_fired
            event_data: {}
          timeout:
            minutes: !input ask_later_wait_time
        - choose:
            - conditions: "{{ wait.trigger and wait.trigger.event.data.actionName == 'fed' }}"
              sequence:
                - service: input_boolean.turn_on
                  target:
                    entity_id: !input input_boolean
                - service: logbook.log
                  data:
                    name: !input notification_title
                    message: !input logbook_message_taken
                    entity_id: !input input_boolean
            - conditions: "{{ wait.trigger and wait.trigger.event.data.actionName == 'later' }}"
              sequence:
                - service: logbook.log
                  data:
                    name: !input notification_title
                    message: !input logbook_message_later
                    entity_id: !input input_boolean
                - delay:
                    minutes: !input ask_later_wait_time
            - conditions: "{{ wait.trigger and wait.trigger.event.data.actionName == 'skip' }}"
              sequence:
                - service: input_boolean.turn_on
                  target:
                    entity_id: !input input_boolean
                - service: logbook.log
                  data:
                    name: !input notification_title
                    message: !input logbook_message_skip
                    entity_id: !input input_boolean
          default:
            - device_id: !input notify_device
              domain: mobile_app
              type: notify
              message: "clear_notification"
              data:
                tag: !input input_boolean
            - service: logbook.log
              data:
                name: !input notification_title
                message: !input logbook_message_no_answer
                entity_id: !input input_boolean
