blueprint:
  name: Tuya Zigbee 1 button remote
  description: "Blueprint for use with Tuya Zigbee 1 button remote on Zigbee2MQTT"
  domain: automation
  input:
    switch:
      name: Tuya Zigbee 1 button remote
      description: Tuya Zigbee 1 button remote to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
    button_1_short_press:
      name: Single Press - Button 1
      description: Action to run on button 1 single press
      default: []
      selector:
        action: null
    button_1_hold:
      name: Hold - Button 1
      description: Action to run on button 1 long press
      default: []
      selector:
        action: null
    button_1_double_press:
      name: Double Press - Button 1
      description: Action to run on button 1 double press
      default: []
      selector:
        action: null

mode: queued

trigger:
  - platform: state
    entity_id: !input switch

condition:
  - "{{ trigger.to_state.state != '' }}"

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == '1_single' }}"
        sequence: !input button_1_short_press
      - conditions:
          - "{{ command == '1_double' }}"
        sequence: !input button_1_double_press
      - conditions:
          - "{{ command == '1_hold' }}"
        sequence: !input button_1_hold
